# Generated by Django 5.2.1 on 2025-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_quizsubmission_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('identification', 'Identification')], max_length=20),
        ),
    ]
