# Generated by Django 5.2.1 on 2025-06-05 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_quizquestion_question_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'teacher', 'course')},
        ),
        migrations.CreateModel(
            name='StudentCourseYearSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.yearsection')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentCourseYearSectionSubject',
        ),
    ]
