# Generated by Django 5.2.1 on 2025-06-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_subject_unique_together_subject_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year_section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.yearsection'),
        ),
    ]
