# Generated by Django 5.2.1 on 2025-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('title', 'quiz_date', 'subject')},
        ),
    ]
