# Generated by Django 5.2.1 on 2025-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subject_year_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='year_section',
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
    ]
