# Generated by Django 5.2.1 on 2025-05-16 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quiz_title_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizchoice',
            unique_together={('question', 'choice')},
        ),
    ]
