# Generated by Django 5.2.1 on 2025-06-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_subject_year_section_subject_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='input_answer',
            field=models.TextField(default='', null=True),
        ),
    ]
