# Generated by Django 5.2.1 on 2025-06-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quizattempt_input_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'teacher', 'course', 'description', 'year')},
        ),
    ]
