@port = 8000
@baseUrl = http://127.0.0.1:{{port}}

### * Get All 
GET {{baseUrl}}/quiz

### * CREATE 
POST {{baseUrl}}/quiz
Content-Type: application/json

{
  "title": "Data Structures",
  "time_limit_minutes": 60,
  "quiz_date": "2025-05-14",
  "subject": 3
}

### * UPDATE (u cant update without the whole required fields!)
PUT {{baseUrl}}/quiz/3
Content-Type: application/json

{
  "title": "Programming",
  "time_limit_minutes": 60,
  "quiz_date": "2025-05-14",
  "subject": 3
}

### * DELETE
DELETE {{baseUrl}}/quiz/4