@port = 8000
@baseUrl = http://127.0.0.1:{{port}}

### * Get All 
GET {{baseUrl}}/quiz

### * CREATE 
POST {{baseUrl}}/quiz
Content-Type: application/json

{
  "title": "Data Structures",
  "quiz_start_date": "2025-05-14 09:00:00",
  "quiz_end_date": "2025-05-14 10:00:00",
  "instructions": "Just answer it, are you stupid???",
  "subject": 1
}

### * UPDATE (u cant update without the whole required fields!)
PUT {{baseUrl}}/quiz/3
Content-Type: application/json

{
  "title": "Programming",
  "quiz_start_date": "2025-05-14 09:00:00",
  "quiz_end_date": "2025-05-14 10:00:00",
  "instructions": "Just answer it, are you stupid???",
  "subject": 3
}

### * DELETE
DELETE {{baseUrl}}/quiz/4