@port = 8000
@baseUrl = http://127.0.0.1:{{port}}

### * Get All 
GET {{baseUrl}}/quiz-submission?search=&student=41&subject=

### * CREATE 
POST {{baseUrl}}/quiz-submission
Content-Type: application/json

{
  "quiz": 7,
  "student": 17
}

### * UPDATE (u cant update without the whole required fields!)
PUT {{baseUrl}}/quiz-submission/1
Content-Type: application/json

{
  "quiz": 7,
  "student": 17,
  "submitted_at": "2025-06-07T12:36:00Z"
}

### * DELETE
DELETE {{baseUrl}}/quiz-submission/4