@port = 8000
@baseUrl = http://127.0.0.1:{{port}}

### * Get All 
GET {{baseUrl}}/quiz-submission

### * CREATE 
POST {{baseUrl}}/quiz-submission
Content-Type: application/json

{
  "quiz": 1,
  "student": 1
}

### * UPDATE (u cant update without the whole required fields!)
PUT {{baseUrl}}/quiz-submission/3
Content-Type: application/json

{
  "quiz": 1,
  "student": 1
}

### * DELETE
DELETE {{baseUrl}}/quiz-submission/4