@port = 8000
@baseUrl = http://127.0.0.1:{{port}}

### * Get All 
GET {{baseUrl}}/user

### * LOGIN 
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "teacher@email.com",
  "password": "123"
}

### * CREATE with role
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "sample_student1",
  "first_name": "student1",
  "middle_name": "student1",
  "last_name": "student1",
  "email": "student1@email.com",
  "password": "123",
  "role": "student"
}

### * CREATE with role
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "teacher1",
  "first_name": "teacher1",
  "middle_name": "teacher1",
  "last_name": "teacher1",
  "email": "teacher1@email.com",
  "password": "123",
  "role": "teacher"
}

### * UPDATE (u cant update without the whole required fields!)
PUT {{baseUrl}}/user/2
Content-Type: application/json

{
  "username": "sample_username",
  "first_name": "Jiro",
  "middle_name": "G",
  "last_name": "Mendador",
  "email": "teacher@email.com",
  "password": "123",
  "role": "teacher"
}

### * DELETE
DELETE {{baseUrl}}/user/1